name: Container image build

on:
  push:
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  container:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ['linux/amd64', 'linux/arm64']
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u doerfli --password-stdin
      - uses: rlespinasse/github-slug-action@v2.x
      - name: build and push image
        run: |
          docker buildx create --use
          docker buildx build --platform ${{ matrix.arch }} -f Dockerfile.enchanted_vault -t ghcr.io/doerfli/airgapped-wallet/enchanted_vault:${{ env.GITHUB_REF_SLUG }} --push .
          docker push ghcr.io/doerfli/airgapped-wallet/enchanted_vault:${{ env.GITHUB_REF_SLUG }}
